#!/usr/bin/python3

import logging
import subprocess
import filecmp
import os


def do(from_, to_):
	from_ = os.path.expanduser(from_)
	to_ = os.path.expanduser(to_)

	if os.path.islink(to_):
		logging.debug('%s already a symlink' % to_)
		return

	if os.path.isfile(to_):
		logging.info('%s already exists but is not a symlink' % to_)

		fn_rel = os.path.dirname(to_) + '/' + from_
		if filecmp.cmp(fn_rel, to_):
			logging.info('file contents are same, deleting %s' % to_)
			os.remove(to_)
		else:
			logging.info('file contents differ, leaving %s intact' % to_)
			return

	logging.info('linking %s to %s' % (from_, to_))

	# the try/except stuff is here only because of python 3.2
	try:
		os.makedirs(os.path.dirname(to_), exist_ok=True)
	except:
		pass

	cmd = 'ln -s %s %s' % (from_, to_)
	subprocess.call(cmd, shell=True)


def main():
	logging.basicConfig(level='INFO')

	do('dotfiles/Xresources', '~/.Xresources')
	do('dotfiles/bash_profile', '~/.bash_profile')
	do('dotfiles/bashrc', '~/.bashrc')
	do('dotfiles/emacs', '~/.emacs')
	do('dotfiles/hgrc', '~/.hgrc')
	do('dotfiles/gitconfig', '~/.gitconfig')
	do('dotfiles/makepkg.conf', '~/.makepkg.conf')
	do('dotfiles/omnirun.conf', '~/.omnirun.conf')
	do('dotfiles/tmux.conf', '~/.tmux.conf')
	do('dotfiles/vimrc', '~/.vimrc')
	do('dotfiles/xbindkeysrc', '~/.xbindkeysrc')
	do('dotfiles/xinitrc', '~/.xinitrc')
	do('dotfiles/zshrc', '~/.zshrc')
	do('dotfiles/zprofile', '~/.zprofile')

	do('../dotfiles/ssh_config', '~/.ssh/config')
	do('../dotfiles/id_rsa_aur', '~/.ssh/id_rsa_aur')
	do('../dotfiles/id_rsa_aur.pub', '~/.ssh/id_rsa_aur.pub')

	do('../dotfiles/i3_config', '~/.i3/config')
	do('../dotfiles/gpg.conf', '~/.gnupg/gpg.conf')
	do('../dotfiles/default.tigervnc', '~/.vnc/default.tigervnc')
	do('../dotfiles/flake8', '~/.config/flake8')
	do('../dotfiles/sway_config', '~/.sway/config')

	do('../../dotfiles/vlcrc', '~/.config/vlc/vlcrc')

	do('../../dotfiles/config.fish', '~/.config/fish/config.fish')
	do('../../../dotfiles/fish_prompt.fish', '~/.config/fish/functions/fish_prompt.fish')
	do('../../../dotfiles/fish_right_prompt.fish', '~/.config/fish/functions/fish_right_prompt.fish')
	do('../../../dotfiles/__fish_print_hostnames.fish', '~/.config/fish/functions/__fish_print_hostnames.fish')


if __name__ == '__main__':
	main()
