#!/bin/sh

ln -s dotfiles/hgrc ~/.hgrc
ln -s dotfiles/gitconfig ~/.gitconfig
ln -s dotfiles/tmux.conf ~/.tmux.conf
ln -s dotfiles/vimrc ~/.vimrc
ln -s dotfiles/xbindkeysrc ~/.xbindkeysrc
ln -s dotfiles/zshrc ~/.zshrc

mkdir -p ~/.i3
ln -s ../dotfiles/i3_config ~/.i3/config
